# 🧑‍🔬 <b>Feature Engineering</b>
1) <b>Profit Margin</b>
2) <b>Shipping Duration</b>
3) <b>Sales Performance Category</b>

    
This notebook explains key concepts used in the FeatureEngineering class<br>
<i>superstore -> utilities (didnt create the class yet)</i>

## <b>Profit Margin</b>

In [9]:
import pandas as pd
from superstore import utilities

try:
    df = pd.read_excel("../Superstore 2019.xls", index_col="Row ID")
except FileNotFoundError:
    raise FileNotFoundError("Change file name to Superstore 2019.xls")

cleaner = utilities.Cleaner(df)
df = cleaner.clean()
df.head(1) # 0 New colums added

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Row ID,,,,,,,,,,,,,,,,,,,,
1,CA-2018-152156,2018-11-08,2018-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136

In [10]:
df["Profit Margin"] = (df["Profit"] / df["Sales"]).round(2) # Adds Profit Margin column by dividing Profit & Sales

## <b>Shipping Duration</b>

In [ ]:
df["Shipping Duration"] = df["Ship Date"] - df["Order Date"] # Adds Shipping Duration column by subtracting Ship Date & Order Date

## <b>Sales Performance Category</b>

In [ ]:
"""
I thought about using the sales average (mean) to create the bins, but due to skew data using quartiles is a much better option. 

Sources: 
https://www.youtube.com/watch?v=MJt6NotH4fY
https://pandas.pydata.org/docs/reference/api/pandas.cut.html
"""

cutoff = [
            df["Sales"].quantile(0), 
            df["Sales"].quantile(0.25), 
            df["Sales"].quantile(0.50), 
            df["Sales"].quantile(0.75), 
            df["Sales"].quantile(1)
        ]

labels = ["Low", "Medium", "High", "Very High"] # 4 categories

df["Sales Performance Category"] = pd.cut(df["Sales"], bins=cutoff, labels=labels, include_lowest=True)

In [ ]:
df.head(5) # 3 new colums are added

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Profit Margin,Shipping Duration,Sales Performance Category
Row ID,,,,,,,,,,,,,,,,,,,,,
1,CA-2018-152156,2018-11-08,2018-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,0.16,3 days,Very High
2,CA-2018-152156,2018-11-08,2018-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,0.30,3 days,Very High
3,CA-2018-138688,2018-06-12,2018-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,0.47,4 days,Low
4,US-2017-108966,2017-10-11,2017-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,-0.40,7 days,Very High
5,US-2017-108966,2017-10-11,2017-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,0.11,7 days,Medium

In [ ]:
df.info() # 3 new colums are added

<class 'pandas.DataFrame'>
Index: 9993 entries, 1 to 9994
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Order ID                    9993 non-null   str
 1   Order Date                  9993 non-null   datetime64[us]
 2   Ship Date                   9993 non-null   datetime64[us]
 3   Ship Mode                   9993 non-null   str
 4   Customer ID                 9993 non-null   str
 5   Customer Name               9993 non-null   str
 6   Segment                     9993 non-null   str
 7   Country/Region              9993 non-null   str
 8   City                        9993 non-null   str
 9   State                       9993 non-null   str
 10  Postal Code                 9993 non-null   Int64
 11  Region                      9993 non-null   str
 12  Product ID                  9993 non-null   str
 13  Category                    9993 non-null   str
 14  Sub-Category                9993 non-null   str
 15  Product Name                9993 non-null   str
 16  Sales                       9993 non-null   float64
 17  Quantity                    9993 non-null   int64
 18  Discount                    9993 non-null   float64
 19  Profit                      9993 non-null   float64
 20  Profit Margin               9993 non-null   float64
 21  Shipping Duration           9993 non-null   timedelta64[us]
 22  Sales Performance Category  9993 non-null   category
dtypes: Int64(1), category(1), datetime64[us](2), float64(4), int64(1), str(13), timedelta64[us](1)
memory usage: 1.8 MB